### ISSUE TITLE
[compute] add VM operations samples

### ISSUE THREAD

**Issue by joshgav** [Azure-Samples/azure-sdk-for-go-samples#102]
Move VM management operations
from: https://github.com/Azure-Samples/virtual-machines-go-manage/blob/master/example.go#L264
to: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/compute - perhaps a new file titled vm_operations.go?

**Comment by mcardosos** [comment]
Will be fixed on https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/91
Currently blocked by https://github.com/Azure/azure-sdk-for-go/issues/1000
