### ISSUE TITLE
[compute] add VM with MSI sample

### ISSUE THREAD

**Issue by joshgav** [Azure-Samples/azure-sdk-for-go-samples#103]
move
from: https://github.com/Azure-Samples/compute-go-msi-vm/blob/master/main.go
to: https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/compute, perhaps a file named `vm_msi.go`?

**Comment by mcardosos** [comment]
Fixed on https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/89
