### ISSUE TITLE
[compute] add VM extensions sample

### ISSUE THREAD

**Issue by joshgav** [Azure-Samples/azure-sdk-for-go-samples#104]
move
from: https://github.com/Azure-Samples/arm-compute-go-vm-extensions
to: https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/compute

What are these samples meant to show? Do they overlap with #103? If possible would be great to cut the code down to just the additional functionality this shows. Thanks!

**Comment by mcardosos** [comment]
Fixed on https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/93
