### ISSUE TITLE
[resource manager] add template deployment sample

### ISSUE THREAD

**Issue by joshgav** [Azure-Samples/azure-sdk-for-go-samples#108]
copy from:
* https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/_quickstarts/deployments.go
* https://github.com/Azure-Samples/resource-manager-go-template-deployment/blob/master/example.go

to: https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/resources

**Comment by mcardosos** [comment]
Fixed in
