### ISSUE TITLE
Get rid of ARM folder dependencies

### ISSUE THREAD

**Issue by mcardosos** [Azure-Samples/azure-sdk-for-go-samples#112]
We should be using services folder

Thank you for your contribution and feedback! Help us review faster by providing the following information:

## This issue is a: (mark with an `x`)

- [ ] bug report
- [ ] request for new sample
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

**Comment by joshgav** [comment]
specifically https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/authorization/auth.go#L9

Thanks!
