### ISSUE TITLE
[storage] How would I stream upload a 10 GB file with configurable concurrency / chunk sizes?

### ISSUE THREAD

**Issue by derekperkins** [Azure-Samples/azure-sdk-for-go-samples#118]
It's pretty obvious with S3 and GCS, but I can't figure out how to do that with Azure. Even uploading a simple small file isn't very obvious, since the storage package combines all the messaging, table and blob components.

S3 https://godoc.org/github.com/aws/aws-sdk-go-v2/service/s3/s3manager#Uploader.UploadWithContext
GCS https://godoc.org/cloud.google.com/go/storage#Writer

**Comment by joshgav** [comment]
@sercanguler, can you help demonstrate this?

**Comment by joshgav** [comment]
@seguler can you help demonstrate this?

**Comment by marstr** [comment]
Closing in favor of Azure/azure-storage-blob-go#39
