### ISSUE TITLE
Parameterize Token Getter

### ISSUE THREAD

**Issue by marstr** [Azure-Samples/azure-sdk-for-go-samples#146]
In `iam.GetResourceManagementToken` we currently hard code the public Azure endpoint: https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/5a201cc36608f52c49cabb0dcca8c7c272f9fc5d/iam/oauth.go#L116.

Can we parameterize the `GetResourceManagementToken` method itself to accept an endpoint so that the same method can be reused for other regions and Stack? Thanks!

// note: edited by @joshgav for clarification

**Comment by vladbarosan** [comment]
This would be fixed when https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/146 happens

**Comment by mcardosos** [comment]
fixed on https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/167
