### ISSUE TITLE
/github.com/azure-samples/azure-sdk-for-go-samples/quickstarts/deploy-vm$ go run main.go

### ISSUE THREAD

**Issue by waytai** [Azure-Samples/azure-sdk-for-go-samples#198]
Thank you for your contribution and feedback! Help us review faster by providing the following information:

## This issue is a: (mark with an `x`)

- [ ] bug report

## Steps to reproduce:
failed to create group: resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '47000f32-1714-4b72-b022-aa1b21cfa03f' could not be found."

and I have changed westus to chinaeast but also report this message

## OS and Go versions:
ubuntu go1.9.2

**Comment by vladbarosan** [comment]
This seems to be caused by either the sub being incorrect. Use the portal or throught the Azure CLI, you can run `az account list`
