### ISSUE TITLE
containerservice example is outdated

### ISSUE THREAD

**Issue by ben-st** [Azure-Samples/azure-sdk-for-go-samples#206]
Thank you for your contribution and feedback! Help us review faster by providing the following information:

## This issue is a: (mark with an `x`)

- [ ] bug report
- [X] request for new sample
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

## Further info:

the current example for managed container service is at: 2017-09-30
https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/containerservice/managedcluster.go#L13

while the latest release is: 2018-03-31
https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerservice/mgmt/2018-03-31/containerservice/version.go#L24

Can we update the sample to the latest containerservice version?

**Comment by joshgav** [comment]
Yes, we'll work on this, thanks!

**Comment by ben-st** [comment]
@joshgav awesome 👍 
thank you for your quick reply and all the best.
