### ISSUE TITLE
az aks get-credentials

### ISSUE THREAD

**Issue by pcj** [Azure-Samples/azure-sdk-for-go-samples#217]
Hi looking for guidance on how to recreate what `az aks get-credentials` does with the go-sdk.  Looks like I want to retrieve a https://godoc.org/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2017-09-30/containerservice#ManagedClusterAccessProfile object but not clear on how to do that with an `aksClient`.

**Comment by sptramer** [comment]
@joshgav Is this a feature available in the SDK right now, or does the project need a request?

**Comment by cfreemoser** [comment]
Any updates?

**Comment by zoheb303** [comment]
are you looking for this : https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/get-access-profile
In containerservice.AccessProfile
// AccessProfile profile for enabling a user to access a managed cluster.
type AccessProfile struct {
	// KubeConfig - Base64-encoded Kubernetes configuration file.
	KubeConfig *[]byte `json:"kubeConfig,omitempty"`
}

**Comment by abdullah-lt** [comment]
Is this a feature available in the SDK right now ?

**Comment by pcj** [comment]
No longer looking at this but will close the issue, hopefully @zoheb303 suggestion will work for future visitors of this thread.
