### ISSUE TITLE
iam and config should move back from internal/

### ISSUE THREAD

**Issue by element-of-surprise** [Azure-Samples/azure-sdk-for-go-samples#218]
Thank you for your contribution and feedback! Help us review faster by providing the following information:

## This issue is a: (mark with an `x`)

- [ ] bug report
- [ ] request for new sample
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)

## Steps to reproduce:
Try any build that relied on iam or config.

## Expected behavior:
That iam and config would not move into an internal/.  Or move.  

So I get that this repo has azure-sdk-for go-samples, samples being key.  But iam and config are useful enough that they should have either started as internal/ or not move out of public.  They probably should belong to the main repo.

So, and probably badly, I was relying on these files while using keyvault.  Changing to internal/ caused my build to break.

The samples are using a centralized library for auth/config, meaning it probably should be down the stack.  I'm going to handle the problem, but this might have broken others.

**Comment by vladbarosan** [comment]
Hi @element-of-surprise you are right those should have been under /internal from the beginning and yes also those shouldn't be taken as a dependency.

As for their usage, did you have a look at the new helpers for auth at https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go ? Those are the supported and recommended methods to use for auth. Let us know if there is anything missing there.

**Comment by element-of-surprise** [comment]
Hey Vlad,

So I've been talking to Martin about these over at Gophercon.  I believe our discussion ended with (and please correct me if I'm wrong Martin) is that the samples should probably not use /internal.  These are examples of how to use a public API and having the needed implementation details in /internal doesn't support a good example for customers.

I had used the auth library in my code, but it wasn't working as intended when I was doing so.  Now, this is probably programming errors on my part, I don't remember what the problem was.  I guess I'm going to find out today as I try to switch over.

My proposal would be to either eliminate the need for the /internal from the examples or migrate that code into the SDK.

--John



________________________________

**Comment by vladbarosan** [comment]
Hi @element-of-surprise  yes we are aiming to eliminate any dependency on what is in /internal and until then we moved it out to /internal so users avoid at least taking a dependency on that.  

We are tracking the improvements to auth here https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/208.

Let us know in the go-autorest of any issue you had there.
