### ISSUE TITLE
running tests fails with "use of internal package not allowed"

### ISSUE THREAD

**Issue by jbw976** [Azure-Samples/azure-sdk-for-go-samples#237]
Thank you for your contribution and feedback! Help us review faster by providing the following information:

## This issue is a: (mark with an `x`)

- [x] bug report
- [ ] request for new sample
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

## Steps to reproduce:
Run steps in https://github.com/Azure-Samples/azure-sdk-for-go-samples#to-run-tests to run the tests:
```
dep ensure
go test -v ./network/
```

## Errors and log messages:
```
> go test -v ./network/
network/ipaddress.go:15:2: use of internal package not allowed
network/ipaddress.go:16:2: use of internal package not allowed
```

## Expected behavior:
The tests to be invoked and execute

## OS and Go versions:
go version go1.10 darwin/amd64
macOS Mojave Version 10.14.1

**Comment by hjarraya** [comment]
This is not a bug, make sure you clone the `azure-sdk-for-go-samples` in the folder `$GOPATH/src/github.com/Azure-Samples/azure-sdk-for-go-samples`.

**Comment by jbw976** [comment]
Thanks @hjarraya, that is the exact path that I had cloned the repo to.
```
jared@Jareds-MacBook-Pro ~/dev/
> cd $GOPATH/src/github.com/Azure-Samples/azure-sdk-for-go-samples
jared@Jareds-MacBook-Pro ~/dev/go/src/github.com/Azure-Samples/azure-sdk-for-go-samples
>
```
I just blew away the entire directory and re-cloned it now and I no longer see this behavior reproducing.  I'm not sure how that fixed it, but it seems to have.  I will close this issue now, thank you.

**Comment by git4raj** [comment]
i did the same. the error keeps coming back. when I import "github.com/Azure-Samples/azure-sdk-for-go-samples/internal/util" - it says "use of internal package not allowed...."

**Comment by git001** [comment]
I have the same problem with @git4raj with `go version go1.14.2 linux/amd64`.
I try to run https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/network/ipaddress.go
