### ISSUE TITLE
fix main test job

### ISSUE THREAD

**Issue by joshgav** [Azure-Samples/azure-sdk-for-go-samples#25]
latest commits led to failure in Jenkins tests, we need to fix

http://azuresdkci.cloudapp.net/view/golang/job/azure-sdk-for-go-samples/

**Comment by mcardosos** [comment]
Jobs are running on Jenkins, on both canary and prod. There is a single service that is not working on canary, but the service capacity is extremely limited. If in the future capacity increases, we could get access to that service.
