### ISSUE TITLE
Keyvault authorization is not working

### ISSUE THREAD

**Issue by rafa-pizzi** [Azure-Samples/azure-sdk-for-go-samples#265]
Thank you for your contribution and feedback! Help us review faster by providing the following information:

## This issue is a: (mark with an `x`)

- [x] bug report
- [ ] request for new sample
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

## Steps to reproduce:
On
https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/keyvault/pass-manager.go#L35
When importing github.com/Azure/azure-sdk-for-go/services/keyvault/auth, this resource does not exist anymore.
Everything under /keyvault/ has moved to api_versions folder, and none have auth.

## Errors and log messages:
`cannot find package (...)`

## Expected behavior:
Package is found

**Comment by jhendrixMSFT** [comment]
I think the `auth` package was accidentally removed.  @ArcturusZhang can you please take a look?

**Comment by ArcturusZhang** [comment]
Sorry about this error. it will be fixed soon in the SDK.

**Comment by ArcturusZhang** [comment]
Hi @rafa-pizzi this issue should be resolved in go SDK version v34.1.0. Please feel free to have another test. If this issue persists, please let me know.
