### ISSUE TITLE
PrintAndLog formatting

### ISSUE THREAD

**Issue by radu-matei** [Azure-Samples/azure-sdk-for-go-samples#37]
Hi, everyone!
Started working on #28 and stumbled upon `PrintAndLog`:

```go
// PrintAndLog writes to stdout and to a logger.
func PrintAndLog(message string) {
	log.Println(message)
	fmt.Println(message)
}
```

The main issue I have with this is that I cannot pass formatted messages - do you think something like below would work?

```go
// PrintfAndLog writes to stdout and to a logger.
func PrintfAndLog(format string, args ...interface{}) {
	log.Printf(format, args...)
	fmt.Printf(format, args...)
}
```

Also, why do we do both `log.Print` and `fmt.Print`?

Update: after using this with the actual test, I understand the need for both - the question is whether we also need to have one with the ability to format the message, as above - maybe `PrintfAndLog`?

[Example of usage for method above here](https://github.com/radu-matei/azure-sdk-for-go-samples/blob/8bde12e9fbf9ea0918768b728c0c19e0b55d4083/containerinstance/containerinstance_test.go#L74):

`helpers.PrintAndLog(fmt.Sprintf("container group name: %v", *c.Name))`

The question is whether this is a valid use case, or the print and log should only be used for well known // Output messages.

An alternative would be to use the `testing` package.

Thanks,
Radu M

**Comment by joshgav** [comment]
Hi Radu! Yes, the PrintAndLog function was added so Go's tests would pick up the output, but we really wanted to use the `testing` package from the beginning. I'm working on refactoring now in #203 and have begun to replace examples with tests. If you have other suggestions please chime in there, thanks!
