### ISSUE TITLE
Container Instance examples cannot be run alone

### ISSUE THREAD

**Issue by mcardosos** [Azure-Samples/azure-sdk-for-go-samples#48]
All 4 examples depend on each other. They should be able to run on their own

Thanks for your contributions and feedback to the samples for Go on Azure!

### This issue is a: (mark with an `x`)
```
- [ ] bug report (consider searching issues before submitting)
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Related errors and log messages
>

### Expected/desired behavior
>

### OS and Go version
> Windows version, Linux distribution and version, macOS version.
> Go version

Thanks again!

**Comment by radu-matei** [comment]
@mcardosos - I assume here we should add the remaining examples for container group (edit, delete)?
