### ISSUE TITLE
deprecate other samples in this org

### ISSUE THREAD

**Issue by vladbarosan** [Azure-Samples/azure-sdk-for-go-samples#81]
- at least the ones which have an equivalent here

**Comment by joshgav** [comment]
related: https://github.com/Azure-Samples/azure-sdk-for-go-samples/issues/27

**Comment by joshgav** [comment]
are any of these still around? the ones in arm/examples are already gone in the dev branch

**Comment by mcardosos** [comment]
While deprecating repos I discovered some of our samples might be incomplete. Added issues for those
