### ISSUE TITLE
Run samples continuously 

### ISSUE THREAD

**Issue by mcardosos** [Azure-Samples/azure-sdk-for-go-samples#86]
run cronjobs at specific hours

**Comment by vladbarosan** [comment]
@mcardosos , @joshgav don't really now what is the value of running at specific hours. Can you please elaborate  ?

**Comment by mcardosos** [comment]
This is so it runs early in the morning, so when we arrive to the office we already have test results and if there is a problem we can work on it. Tests can run while not in the office.

**Comment by vladbarosan** [comment]
@mcardosos I fail to see how WHEN we detect is important. Let's say an issue starts to happen at 3 PM and we run the tests at 7:00 AM. That means that the issue is there since 3 PM but we only detect it at 7 AM. 

If we really want to catch issues as fast as possible, the only way to do that is continuous testing

**Comment by mcardosos** [comment]
Continuous testing is also a possibility, yes.

**Comment by joshgav** [comment]
doesn't matter that much what exact time we run them, but we should run them at least once a day, preferably once in the morning and once in the afternoon/evening

**Comment by vladbarosan** [comment]
@joshgav i dont think we can run them twice a day in travis. It allows to set it to run daily and I think mariana has that set up already. If that is the case I would change this to be Run the samples continuously 
(e.g. using Geneva Runners )

**Comment by mcardosos** [comment]
If you want to be able to run them more than once a day (and want to solve this issue fast), the best rout is to run them on jenkins. In the future I could look into using the geneva runners.

**Comment by vladbarosan** [comment]
well I would go for that if we want truly to catch issues as they happen ( although it might be just a temporary glitch with ARM or the service. 

We can rename it and decide on next sprint planning.

**Comment by joshgav** [comment]
if it's a hassle once a day is fine, awesome that we have that set up. thanks!

**Comment by marstr** [comment]
This is done.
