### ISSUE TITLE
Dev and master branch should be synced often

### ISSUE THREAD

**Issue by mcardosos** [Azure-Samples/azure-sdk-for-go-samples#88]
Dev branch is running tests using the sdk and runtime dev branches. For that reason, a different dep file is needed so `dep ensure` can pull the correct repo branches. SO dev and master branches in this repo should be synced, with the only difference being the dep file

Thank you for your contribution and feedback! Help us review faster by providing the following information:

## This issue is a: (mark with an `x`)

- [ ] bug report
- [ ] request for new sample
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

**Comment by marstr** [comment]
Stale, closing
