### ISSUE TITLE
Samples app ID does not have enough permissions to create AD apps

### ISSUE THREAD

**Issue by mcardosos** [Azure-Samples/azure-sdk-for-go-samples#94]
`bee3737f-b06f-444f-b3c3-5b0f3fce46ea` client ID can't be used to create Active Directory apps. It fails with 403. But the Azure CLI client ID has enough permissions: `04b07795-8ddb-461a-bbee-02f9e1bf7b46`.
cc @joshgav

**Comment by joshgav** [comment]
@mcardosos can we create a client in our test tenant with the right permissions and replace the current one?

**Comment by vladbarosan** [comment]
Ping @mcardoso

**Comment by mcardosos** [comment]
Instead of using a provided clientID, users need to create their own clientID
